leg_detector:
  ros__parameters:
    #------------------------------------------------------
    # CLUSTERING
    #------------------------------------------------------
    cluster_eps: 0.06
    # min_cluster_points: 5
    # max_angle_gap: 20
    # adaptive_eps_gain: 1.5
    # adaptive_eps_offset: 0.01
    #------------------------------------------------------
    # GEOMETRY FILTER
    #------------------------------------------------------
    # min_cluster_width: 0.03
    # max_cluster_width: 0.30
    #------------------------------------------------------
    # VISUALIZATION
    #------------------------------------------------------
    # person_marker_hight: 0.20
    # person_marker_z: 0.80
    #------------------------------------------------------
    # Controller
    #------------------------------------------------------
    target_distance: 1.0
    kp_linear: 1.80
    kp_angular: 2.50
    stop_radius: 0.2
    danger_radius: 0.2